-- ANSWER 1
SELECT
	*,
	ROUND(BUDGET * 100.0 / SUM(BUDGET) OVER (), 2) || '%' AS PCT_OF_BUDGET
FROM
	MARKETING.CAMPAIGNS

-- ANSWER 2
SELECT
	EMPLOYEE_ID,
	STORE_ID,
	SALARY,
	ROUND(
		AVG(SALARY) OVER (
			PARTITION BY
				STORE_ID
		),
		2
	) AS AVG_SALARY,
	SALARY - ROUND(
		AVG(SALARY) OVER (
			PARTITION BY
				STORE_ID
		),
		2
	) AS DIFF
FROM
	STORES.EMPLOYEES;

-- ANSWER 3
SELECT
	*,
	COUNT(PRICE) OVER (
		PARTITION BY
			BRAND_ID
	) AS COUNT,
	MIN(PRICE) OVER (
		PARTITION BY
			BRAND_ID
	) AS MIN_SALARY,
	MAX(PRICE) OVER (
		PARTITION BY
			BRAND_ID
	) AS MAX_SALARY
FROM
	PRODUCTS.PRODUCTS

-- ANSWER 4
SELECT
	*,
	ROUND(
		AVG(NET_TOTAL) OVER (
			PARTITION BY
				STORE_ID
		),
		2
	) AS STORE_AVG_REV,
	CASE
		WHEN NET_TOTAL > (
			ROUND(
				AVG(NET_TOTAL) OVER (
					PARTITION BY
						STORE_ID
				),
				2
			) * 3
		) THEN 'High Value'
		ELSE 'Low'
	END AS FLAG
FROM
	SALES.ORDERS

-- ANSWER 5
WITH
	TICK_COUNT AS (
		SELECT
			CREATED_DATE,
			COUNT(TICKET_ID) AS TICK_CNT
		FROM
			SUPPORT.TICKETS
		GROUP BY
			CREATED_DATE
	),
	CUMULATIVE AS (
		SELECT
			*,
			SUM(TICK_CNT) OVER (
				ORDER BY
					CREATED_DATE
			) AS CUMM_CNT
		FROM
			TICK_COUNT
	)
SELECT
	*
FROM
	CUMULATIVE
WHERE
	CUMM_CNT >= 5000;


-- ANSWER 6
WITH
	RUN_TOTAL AS (
		SELECT
			*,
			SUM(NET_TOTAL) OVER (
				PARTITION BY
					STORE_ID
				ORDER BY
					ORDER_DATE,
					ORDER_ID
			) AS RUNNING_TOTAL
		FROM
			SALES.ORDERS
	)
SELECT
	STORE_ID,
	MIN(ORDER_DATE) AS FIRST_ORDER_CROSS_1CR
FROM
	RUN_TOTAL
WHERE
	RUNNING_TOTAL >= 10000000
GROUP BY
	STORE_ID
ORDER BY
	FIRST_ORDER_CROSS_1CR
LIMIT
	1;

-- ANSWER 7
WITH
	DAILY_PG_COUNT AS (
		SELECT
			DATE_TRUNC('day', VIEW_TIMESTAMP) AS DATE,
			COUNT(VIEW_ID) AS PAGE_VIEW
		FROM
			WEB_EVENTS.PAGE_VIEWS
		GROUP BY
			DATE_TRUNC('day', VIEW_TIMESTAMP)
		ORDER BY
			DATE_TRUNC('day', VIEW_TIMESTAMP)
	)
SELECT
	*,
	SUM(PAGE_VIEW) OVER (
		ORDER BY
			DATE
	) AS RUNN_PAGE_VIEW,
	ROUND(
		PAGE_VIEW * 100.0 / SUM(PAGE_VIEW) OVER (
			ORDER BY
				DATE
		),
		2
	) AS PCT_OF_PAGE_VIEW
FROM
	DAILY_PG_COUNT;

-- ANSWER 8
WITH
	ORDER_TOTAL AS (
		SELECT
			*,
			EXTRACT(
				YEAR
				FROM
					ORDER_DATE
			) AS YEARS,
			EXTRACT(
				QUARTER
				FROM
					ORDER_DATE
			) AS QUARTERS
		FROM
			SALES.ORDERS
	)
SELECT
	*,
	sum(net_total) over(partition by years, quarters order by order_date,order_id) as running_total
FROM
	ORDER_TOTAL;

-- ANSWER 9
SELECT
	SUM(NET_TOTAL) OVER () AS REV1,
	SUM(NET_TOTAL) OVER (
		ORDER BY
			ORDER_DATE ROWS BETWEEN UNBOUNDED PRECEDING
			AND UNBOUNDED FOLLOWING
	) AS REV2
FROM
	SALES.ORDERS;

-- BOTH OUTPUT ARE SAME 

-- ANSWER 10
SELECT
	*,
	ROUND(
		AVG(BUDGET) OVER (
			ROWS BETWEEN CURRENT ROW
			AND 3 FOLLOWING
		),
		2
	) AS AVG_BUDGET
FROM
	MARKETING.CAMPAIGNS

-- ANSWER 11
SELECT
	*,
	MIN(NET_TOTAL) OVER (
		ROWS BETWEEN 4 PRECEDING
		AND CURRENT ROW
	) MIN_LAST_5,
	COUNT(*) OVER (
		ROWS BETWEEN 4 PRECEDING
		AND CURRENT ROW
	) AS WINDOW_COUNT
FROM
	SALES.ORDERS;

-- ANSWER 12
SELECT
	*,
	SUM(NET_TOTAL) OVER (
		ORDER BY
			ORDER_DATE,
			ORDER_ID ROWS BETWEEN UNBOUNDED PRECEDING
			AND CURRENT ROW
	) AS DEFAULT_FRAME,
	SUM(NET_TOTAL) OVER (
		ORDER BY
			ORDER_DATE,
			ORDER_ID ROWS BETWEEN 4 PRECEDING
			AND CURRENT ROW
	) AS LIMITED_5_FRAME
FROM
	SALES.ORDERS

-- ANSWER 13
SELECT
	*,
	ROUND(
		AVG(SALARY) OVER (
			ORDER BY
				EMPLOYEE_ID ROWS BETWEEN 1 PRECEDING
				AND 1 FOLLOWING
		),
		2
	) AS CENTERED_AVG
FROM
	STORES.EMPLOYEES

-- ANSWER 14
WITH
	DAILY_ORDER AS (
		SELECT
			DATE_TRUNC('day', ORDER_DATE) AS DAYS,
			COUNT(*) AS ORDER_COUNT
		FROM
			SALES.ORDERS
		GROUP BY
			DATE_TRUNC('day', ORDER_DATE)
	)
SELECT
	*,
	ROUND(
		AVG(ORDER_COUNT) OVER ( ROWS BETWEEN 6 PRECEDING
				AND CURRENT ROW
		),
		2
	) AS MOVING_AVG_7_DAYS
FROM
	DAILY_ORDER

-- ANSWER 15
WITH
	CLEAN AS (
		SELECT
			DATE_TRUNC('day', ORDER_DATE) AS DATE,
			SUM(NET_TOTAL) AS DAILY_TOTAL
		FROM
			SALES.ORDERS
		GROUP BY
			DATE_TRUNC('day', ORDER_DATE)
	)
SELECT
	*,
	ROUND(
		AVG(DAILY_TOTAL) OVER (
			ORDER BY
				DATE ROWS BETWEEN 6 PRECEDING
				AND CURRENT ROW
		),
		2
	) AS AVG_7_DAY,
	ROUND(
		AVG(DAILY_TOTAL) OVER (
			ORDER BY
				DATE ROWS BETWEEN 13 PRECEDING
				AND CURRENT ROW
		),
		2
	) AS AVG_14_DAY,
	ROUND(
		AVG(DAILY_TOTAL) OVER (
			ORDER BY
				DATE ROWS BETWEEN 29 PRECEDING
				AND CURRENT ROW
		),
		2
	) AS AVG_30_DAY
FROM
	CLEAN

-- ANSWER 16
WITH
	DAILY_REV AS (
		SELECT
			DATE_TRUNC('day', ORDER_DATE) AS DAYS,
			ROUND(AVG(NET_TOTAL), 2) AS AVG_REV
		FROM
			SALES.ORDERS
		GROUP BY
			DATE_TRUNC('day', ORDER_DATE)
	),
	AVG_CALC AS (
		SELECT
			*,
			ROUND(
				AVG(AVG_REV) OVER (
					ORDER BY
						DAYS ROWS BETWEEN 6 PRECEDING
						AND CURRENT ROW
				),
				0
			) AS WEEKLY_AVG
		FROM
			DAILY_REV
	)
SELECT
	*,
	ROUND(AVG_REV * 100.0 / WEEKLY_AVG, 2) AS PCT,
	CASE
		WHEN AVG_REV * 100.0 / WEEKLY_AVG > 200 THEN 'MEGA SPIKE'
		ELSE 'Normal'
	END AS SPIKE_TYPE
FROM
	AVG_CALC

-- ANSWER 17
WITH
	CLEAN AS (
		SELECT
			STORE_ID,
			DATE_TRUNC('day', ORDER_DATE) AS DATE,
			SUM(NET_TOTAL) AS DAILY_TOTAL
		FROM
			SALES.ORDERS
		GROUP BY
			STORE_ID,
			DATE_TRUNC('day', ORDER_DATE)
	),
	-- A smooth trend = values change gradually (low fluctuation) STDDEV()
	-- A noisy trend = values jump up/down a lot
	-- STDDEV - avg value of how values are far from mean
	FINAL_TABLE AS (
		SELECT
			*,
			ROUND(
				AVG(DAILY_TOTAL) OVER (
					PARTITION BY
						STORE_ID
					ORDER BY
						DATE ROWS BETWEEN 6 PRECEDING
						AND CURRENT ROW
				),
				2
			) AS AVG_7_DAY
		FROM
			CLEAN
	)
SELECT
	STORE_ID,
	round(STDDEV(AVG_7_DAY),2) AS DEVIATION
FROM
	FINAL_TABLE
GROUP BY
	STORE_ID
ORDER BY
	DEVIATION
LIMIT
	1

-- ANSWER 18
WITH
	CLEAN AS (
		SELECT
			DATE_TRUNC('day', ORDER_DATE) AS DAYS,
			ROUND(AVG(NET_TOTAL), 2) AS AVERAGE
		FROM
			SALES.ORDERS
		GROUP BY
			DATE_TRUNC('day', ORDER_DATE)
	),
	AVG_CALC AS (
		SELECT
			*,
			ROUND(
				AVG(AVERAGE) OVER (
					ORDER BY
						DAYS ROWS BETWEEN 6 PRECEDING
						AND CURRENT ROW
				),
				2
			) AS AVG_7_DAYS,
			ROUND(
				AVG(AVERAGE) OVER (
					ORDER BY
						DAYS ROWS BETWEEN 29 PRECEDING
						AND CURRENT ROW
				),
				2
			) AS AVG_30_DAYS
		FROM
			CLEAN
	)
SELECT
	*,
	CASE
		WHEN AVG_7_DAYS > AVG_30_DAYS THEN 'BUY SIGNAL'
		ELSE 'SELL SIGNAL'
	END AS SUGGESTION
FROM
	AVG_CALC

-- ANSWER 19
WITH
	Q4 AS (
		SELECT
			*,
			EXTRACT(
				QUARTER
				FROM
					ORDER_DATE
			) AS QTR
		FROM
			SALES.ORDERS
		WHERE
			EXTRACT(
				QUARTER
				FROM
					ORDER_DATE
			) = 4
	)
SELECT
	*,
	SUM(NET_TOTAL) OVER (
		PARTITION BY
			STORE_ID
	) AS STORE_TOTAL,
	SUM(NET_TOTAL) OVER (
		PARTITION BY
			STORE_ID
		ORDER BY
			ORDER_DATE
	) AS CUMM_STORE_TOTAL
FROM
	Q4;

-- ANSWER 20
WITH
	CLEAN AS (
		SELECT
			*,
			SUM(NET_TOTAL) OVER (
				PARTITION BY
					STORE_ID
			) AS STORE_REV
		FROM
			SALES.ORDERS
	),
	PCT AS (
		SELECT
			*,
			ROUND(NET_TOTAL * 100.0 / STORE_REV, 6) AS PCT,
			RANK() OVER (
				PARTITION BY
					STORE_ID
				ORDER BY
					NET_TOTAL
			) AS RNK
		FROM
			CLEAN
	)
SELECT
	*
FROM
	PCT
WHERE
	RNK <= 5;

-- ANSWER 21
WITH
	MONTHLY AS (
		SELECT
			DATE_TRUNC('month', ORDER_DATE) AS MONTHS,
			SUM(NET_TOTAL) AS MONTH_REV
		FROM
			SALES.ORDERS
		GROUP BY
			DATE_TRUNC('month', ORDER_DATE)
	)
SELECT
	*,
	SUM(MONTH_REV) OVER (
		PARTITION BY
			EXTRACT(
				YEAR
				FROM
					MONTHS
			)
		ORDER BY
			MONTHS
	) AS YTD
FROM
	MONTHLY

-- ANSWER 22
WITH
	DAILY_REVENUE AS (
		SELECT
			DATE_TRUNC('day', ORDER_DATE) AS DATE,
			SUM(NET_TOTAL) AS DAILY_TOTAL
		FROM
			SALES.ORDERS
		GROUP BY
			DATE_TRUNC('day', ORDER_DATE)
	)
SELECT
	*,
	AVG(DAILY_TOTAL) OVER (
		ORDER BY
			DATE ROWS BETWEEN 6 PRECEDING
			AND CURRENT ROW
	) AS AVG_7_DAY,
	COUNT(DAILY_TOTAL) OVER (
		ORDER BY
			DATE ROWS BETWEEN 6 PRECEDING
			AND CURRENT ROW
	) AS FRAMESIZE
FROM
	DAILY_REVENUE

-- ANSWER 23
WITH
	DAILY_REVENUE AS (
		SELECT
			DATE_TRUNC('day', ORDER_DATE) AS DATE,
			SUM(NET_TOTAL) AS DAILY_TOTAL
		FROM
			SALES.ORDERS
		GROUP BY
			DATE_TRUNC('day', ORDER_DATE)
	),
	SEVEN_DAY_AVG AS (
		SELECT
			*,
			AVG(DAILY_TOTAL) OVER (
				ORDER BY
					DATE ROWS BETWEEN 6 PRECEDING
					AND CURRENT ROW
			) AS AVG_7_DAY,
			COUNT(DAILY_TOTAL) OVER (
				ORDER BY
					DATE ROWS BETWEEN 6 PRECEDING
					AND CURRENT ROW
			) AS FRAMESIZE
		FROM
			DAILY_REVENUE
	)
SELECT
	*,
	CASE
		WHEN DAILY_TOTAL > 1.5 * AVG_7_DAY THEN 'SPIKE'
		WHEN DAILY_TOTAL < 0.5 * AVG_7_DAY THEN 'DIP'
		ELSE 'NORMAL'
	END
FROM
	SEVEN_DAY_AVG

-- ANSWER 24
WITH
	DAILY_REVENUE AS (
		SELECT
			DATE_TRUNC('day', ORDER_DATE) AS DATE,
			SUM(NET_TOTAL) AS DAILY_TOTAL
		FROM
			SALES.ORDERS
		GROUP BY
			DATE_TRUNC('day', ORDER_DATE)
	)
SELECT
	*,
	SUM(DAILY_TOTAL) OVER (
		PARTITION BY
			EXTRACT(
				YEAR
				FROM
					DATE
			)
		ORDER BY
			DATE
	) AS RUNNING_YTD_TOTAL,
	ROUND(
		AVG(DAILY_TOTAL) OVER (
			ORDER BY
				DATE ROWS BETWEEN 6 PRECEDING
				AND CURRENT ROW
		),
		2
	) AS AVG_7_DAYS,
	ROUND(
		AVG(DAILY_TOTAL) OVER (
			ORDER BY
				DATE ROWS BETWEEN 29 PRECEDING
				AND CURRENT ROW
		),
		2
	) AS AVG_30_DAYS
FROM
	DAILY_REVENUE