-- ANSWER 1
SELECT
	PRODUCT_ID,
	PRODUCT_NAME,
	(
		SELECT
			ROUND(AVG(PRICE), 0)
		FROM
			PRODUCTS.PRODUCTS
	) AS AVG_PRICE
FROM
	PRODUCTS.PRODUCTS
WHERE
	PRICE > (
		SELECT
			ROUND(AVG(PRICE), 0)
		FROM
			PRODUCTS.PRODUCTS
	)

-- ANSWER 2
SELECT
	S.STORE_ID,
	S.STORE_NAME,
	SUM(OI.NET_AMOUNT) AS STORE_REVENUE,
	(
		SELECT
			SUM(OI.NET_AMOUNT)
		FROM
			SALES.ORDER_ITEMS OI
	) AS TOTAL_REVENUE,
	ROUND(
		SUM(OI.NET_AMOUNT) * 100.0 /
		(
		SELECT
			SUM(OI.NET_AMOUNT)
		FROM
			SALES.ORDER_ITEMS OI
		),2
	) AS PCT_OF_TOTAL
FROM
	STORES.STORES S
	JOIN SALES.ORDERS O USING (STORE_ID)
	JOIN SALES.ORDER_ITEMS OI USING (ORDER_ID)
GROUP BY
	S.STORE_ID,
	S.STORE_NAME
ORDER BY PCT_OF_TOTAL;

-- ANSWER 3
SELECT
	TICKET_ID,
	CATEGORY,
	EXTRACT(
		HOURS
		FROM
			(RESOLVED_DATE - CREATED_DATE)
	) AS RESOLUTION_HOURS
FROM
	SUPPORT.TICKETS
WHERE
	EXTRACT(
		HOURS
		FROM
			(RESOLVED_DATE - CREATED_DATE)
	) > (
		SELECT
			AVG(
				EXTRACT(
					HOURS
					FROM
						(RESOLVED_DATE - CREATED_DATE)
				)
			)
		FROM
			SUPPORT.TICKETS
		WHERE
			RESOLVED_DATE IS NOT NULL
	);

    -- ANSWER 4
    SELECT
	EMPLOYEE_ID,
	FIRST_NAME
FROM
	STORES.EMPLOYEES
WHERE
	employee_id IN (
		SELECT
			employee_id
		FROM
			STORES.EMPLOYEES
		WHERE
			ROLE = 'Store Manager'
	)

-- ANSWER 5
SELECT
	ORDER_ID,
	order_status
FROM
	SALES.ORDERS
WHERE
	ORDER_ID NOT IN (
		SELECT
			ORDER_ID
		FROM
			SALES.ORDERS
		WHERE
			ORDER_STATUS = 'Returned'
	)

-- ANSWER 6
SELECT
	EMPLOYEE_ID,
	FIRST_NAME
FROM
	STORES.EMPLOYEES
WHERE
	DEPT_ID IN (
		SELECT
			DEPT_ID
		FROM
			STORES.EMPLOYEES
		GROUP BY
			DEPT_ID
		HAVING
			COUNT(*) > 300
	)

-- ANSWER 7
SELECT
	COUNT(*) AS QUALIFIED_ORDER
FROM
	SALES.PAYMENTS
WHERE
	AMOUNT > ANY (
		SELECT
			AMOUNT
		FROM
			SALES.PAYMENTS
		WHERE
			PAYMENT_MODE = 'Cash'
	)

-- ANSWER 8
SELECT
	COUNT(*) AS TOTAL_ORDER
FROM
	SALES.ORDERS
WHERE
	NET_TOTAL > ALL (
		SELECT
			O.NET_TOTAL
		FROM
			SALES.ORDERS O
			JOIN SALES.PAYMENTS P USING (ORDER_ID)
		WHERE
			P.PAYMENT_MODE = 'Gift Card'
	)

-- ANSWER 9
SELECT
	ROLE,
	COUNT(*) AS EMP_COUNT
FROM
	STORES.EMPLOYEES
WHERE
	SALARY < ALL (
		SELECT
			SALARY
		FROM
			STORES.EMPLOYEES
		WHERE
			ROLE = 'Regional Manager'
	)
	AND SALARY > ALL (
		SELECT
			SALARY
		FROM
			STORES.EMPLOYEES
		WHERE
			ROLE = 'Cashier'
	)
GROUP BY
	ROLE
ORDER BY
	EMP_COUNT

-- ANSWER 10
SELECT
	CUST_ID,
	TOTAL_SPEND
FROM
	(
		SELECT
			CUST_ID,
			SUM(NET_TOTAL) AS TOTAL_SPEND
		FROM
			SALES.ORDERS
		GROUP BY
			CUST_ID
	) AS CUSTOMER_TOTAL
WHERE
	TOTAL_SPEND > (
		SELECT
			TOTAL_SPEND
		FROM
			(
				SELECT
					CUST_ID,
					SUM(NET_TOTAL) AS TOTAL_SPEND
				FROM
					SALES.ORDERS
				GROUP BY
					CUST_ID
				ORDER BY
					TOTAL_SPEND
				LIMIT
					1
				OFFSET
					(
						SELECT
							COUNT(DISTINCT CUST_ID) / 2
						FROM
							SALES.ORDERS
					)
			) AS MEDIAN_TABLE
	)

-- ANSWER 11
SELECT
	C.CATEGORY_NAME,
	CS.PRODUCT_COUNT,
	CS.TOTAL_REVENUE,
	CS.AVG_PRODUCT_PRICE
FROM
	(
		SELECT
			B.CATEGORY_ID,
			COUNT(DISTINCT P.PRODUCT_ID) AS PRODUCT_COUNT,
			SUM(OI.NET_AMOUNT) AS TOTAL_REVENUE,
			ROUND(AVG(P.PRICE), 0) AS AVG_PRODUCT_PRICE
		FROM
			PRODUCTS.PRODUCTS P
			JOIN CORE.DIM_BRAND B USING (BRAND_ID)
			JOIN SALES.ORDER_ITEMS OI ON P.PRODUCT_ID = OI.PROD_ID
		GROUP BY
			B.CATEGORY_ID
	) CS
	JOIN CORE.DIM_CATEGORY C USING (CATEGORY_ID)
ORDER BY
	CS.TOTAL_REVENUE DESC

-- ANSWER 12
SELECT
	S.STORE_ID,
	S.STORE_NAME,
	STORE_REV.STORE_REVENUE,
	COMPANY_REV.COMPANY_REVENUE,
	ROUND(
		STORE_REV.STORE_REVENUE * 100.0 / COMPANY_REV.COMPANY_REVENUE,
		2
	) PCT_STORE_PER_COMPANY
FROM
	(
		SELECT
			STORE_ID,
			SUM(NET_TOTAL) AS STORE_REVENUE
		FROM
			SALES.ORDERS
		GROUP BY
			STORE_ID
	) STORE_REV
	JOIN STORES.STORES S USING (STORE_ID)
	CROSS JOIN (
		SELECT
			SUM(NET_TOTAL) AS COMPANY_REVENUE
		FROM
			SALES.ORDERS
	) COMPANY_REV
ORDER BY
	STORE_REV.STORE_REVENUE DESC

-- ANSWER 13
SELECT
	PRODUCT_NAME,
	PRICE
FROM
	PRODUCTS.PRODUCTS
WHERE
	PRICE > (
		SELECT
			ROUND(AVG(PRICE), 0)
		FROM
			PRODUCTS.PRODUCTS
	)
ORDER BY
	PRICE

-- ANSWER 14
SELECT
	EMPLOYEE_ID,
	FIRST_NAME,
	SALARY,
	(
		SELECT
			MAX(SALARY)
		FROM
			STORES.EMPLOYEES
	) AS COMPANY_MAX_SALARY
FROM
	STORES.EMPLOYEES;

-- ANSWER 15
SELECT
	STORE_ID,
	DELIVERED_ORDER_REVENUE
FROM
	(
		SELECT
			STORE_ID,
			SUM(NET_TOTAL) AS DELIVERED_ORDER_REVENUE
		FROM
			SALES.ORDERS
		WHERE
			ORDER_STATUS = 'Delivered'
		GROUP BY
			STORE_ID
	) STORE_REVENUE
WHERE
	DELIVERED_ORDER_REVENUE > (
		SELECT
			AVG(DELIVERED_ORDER_REVENUE)
		FROM
			(
				SELECT
					SUM(NET_TOTAL) AS DELIVERED_ORDER_REVENUE
				FROM
					SALES.ORDERS
				WHERE
					ORDER_STATUS = 'Delivered'
				GROUP BY
					STORE_ID
			) AVG_STORE_REVENUE
	)
ORDER BY
	DELIVERED_ORDER_REVENUE;

-- ANSWER 16
SELECT
    STORE_ID,
    NET_TOTAL,
    ROUND(
        (NET_TOTAL * 100.0) /
        (
            SELECT SUM(NET_TOTAL)
            FROM SALES.ORDERS
        ),
        6
    ) AS PCT_OF_COMPANY_REV
FROM SALES.ORDERS;

-- ANSWER 17
SELECT
	CUSTOMER_ID,
	FIRST_NAME
FROM
	CUSTOMERS.CUSTOMERS
WHERE
	CUSTOMER_ID IN (
		SELECT
			CUST_ID
		FROM
			SALES.ORDERS
	)
	AND CUSTOMER_ID NOT IN (
		SELECT
			CUSTOMER_ID
		FROM
			CUSTOMERS.REVIEWS
		WHERE
			CUSTOMER_ID IS NOT NULL
	)

-- ANSWER 18
SELECT
	EMPLOYEE_ID,
	FIRST_NAME,
	STORE_ID
FROM
	STORES.EMPLOYEES
WHERE
	EMPLOYEE_ID IN (
		SELECT
			AGENT_ID
		FROM
			SUPPORT.TICKETS
		WHERE
			PRIORITY = 'Critical'
	)

-- ANSWER 19
SELECT
	PRODUCT_ID,
	PRODUCT_NAME
FROM
	PRODUCTS.PRODUCTS
WHERE
	PRODUCT_ID IN (
		SELECT
			PROD_ID
		FROM
			SALES.ORDER_ITEMS
	)
	AND PRODUCT_ID NOT IN (
		SELECT
			PROD_ID
		FROM
			SALES.RETURNS
	)

-- ANSWER 20
SELECT DISTINCT
	PAYMENT_MODE
FROM
	SALES.PAYMENTS
WHERE
	ORDER_ID IN (
		SELECT
			ORDER_ID
		FROM
			SALES.ORDERS
		WHERE
			CUST_ID IN (
				SELECT
					CUSTOMER_ID
				FROM
					SALES.PAYMENTS P
					JOIN SALES.ORDERS O USING (ORDER_ID)
					JOIN CUSTOMERS.CUSTOMERS C ON O.CUST_ID = C.CUSTOMER_ID
					JOIN LOYALTY.MEMBERS M USING (CUSTOMER_ID)
					JOIN LOYALTY.TIERS T USING (TIER_ID)
				where t.tier_name = 'Platinum'
			)
	)

-- ANSWER 21
SELECT
	COUNT(*) AS EMP_COUNT,
	ROLE
FROM
	STORES.EMPLOYEES
WHERE
	EMPLOYEE_ID > ALL (
		SELECT
			EMPLOYEE_ID
		FROM
			STORES.EMPLOYEES
		WHERE
			DEPT_ID = 5
	)
group by role;

-- ANSWER 22
SELECT
	*
FROM
	CORE.DIM_CATEGORY
	JOIN ( --product count and avg product price
		SELECT
			B.CATEGORY_ID,
			COUNT(DISTINCT P.PRODUCT_ID) AS PRODUCT_COUNT,
			ROUND(AVG(P.PRICE), 2) AS PRODUCT_AVG
		FROM
			PRODUCTS.PRODUCTS P
			JOIN CORE.DIM_BRAND B USING (BRAND_ID)
		GROUP BY
			B.CATEGORY_ID
	) USING (CATEGORY_ID)
	JOIN ( --total revenue category wise
		SELECT
			B.CATEGORY_ID,
			SUM(NET_AMOUNT) AS REVENUE
		FROM
			SALES.ORDER_ITEMS OI
			JOIN PRODUCTS.PRODUCTS P ON OI.PROD_ID = P.PRODUCT_ID
			JOIN CORE.DIM_BRAND B USING (BRAND_ID)
		GROUP BY
			B.CATEGORY_ID
	) USING (CATEGORY_ID)
	JOIN ( --derived table for top product by revenue
		SELECT
			T1.CATEGORY_ID,
			T1.PRODUCT_ID AS BEST_PRODUCT
		FROM
			( --all product with its revenue category wise
				SELECT
					P.PRODUCT_ID,
					B.CATEGORY_ID,
					SUM(NET_AMOUNT) AS PRODUCT_REVENUE
				FROM
					SALES.ORDER_ITEMS OI
					JOIN PRODUCTS.PRODUCTS P ON P.PRODUCT_ID = OI.PROD_ID
					JOIN CORE.DIM_BRAND B USING (BRAND_ID)
				GROUP BY
					P.PRODUCT_ID,
					B.CATEGORY_ID
				ORDER BY
					B.CATEGORY_ID ASC,
					PRODUCT_REVENUE DESC
			) T1
			JOIN (
				-- B) Max product price, category wise (by grouping category in same sub-que	ry)
				SELECT
					CATEGORY_ID,
					MAX(PRODUCT_REVENUE) AS MAX_REVENUE
				FROM
					(
						SELECT
							P.PRODUCT_ID,
							B.CATEGORY_ID,
							SUM(NET_AMOUNT) AS PRODUCT_REVENUE
						FROM
							SALES.ORDER_ITEMS OI
							JOIN PRODUCTS.PRODUCTS P ON P.PRODUCT_ID = OI.PROD_ID
							JOIN CORE.DIM_BRAND B USING (BRAND_ID)
						GROUP BY
							P.PRODUCT_ID,
							B.CATEGORY_ID
						ORDER BY
							B.CATEGORY_ID ASC,
							PRODUCT_REVENUE DESC
					)
				GROUP BY
					CATEGORY_ID
			) T2 ON T1.CATEGORY_ID = T2.CATEGORY_ID
			AND T1.PRODUCT_REVENUE = T2.MAX_REVENUE --IMP: match product price & category in both tables
	) USING (CATEGORY_ID)

-- ANSWER 23
SELECT
	CURR.MONTH,
	CURR.TOTAL_REVENUE
FROM
	(
		SELECT
			DATE_TRUNC('months', ORDER_DATE) AS MONTH,
			EXTRACT(
				YEAR
				FROM
					ORDER_DATE
			) AS YEAR_NO,
			SUM(NET_TOTAL) AS TOTAL_REVENUE
		FROM
			SALES.ORDERS
		GROUP BY
			DATE_TRUNC('months', ORDER_DATE),
			EXTRACT(
				YEAR
				FROM
					ORDER_DATE
			)
	) CURR
WHERE
	CURR.TOTAL_REVENUE > ALL (
		SELECT
			PREV.TOTAL_REVENUE
		FROM
			(
				SELECT
					DATE_TRUNC('months', ORDER_DATE) AS MONTH,
					EXTRACT(
						YEAR
						FROM
							ORDER_DATE
					) AS YEAR_NO,
					SUM(NET_TOTAL) AS TOTAL_REVENUE
				FROM
					SALES.ORDERS
				GROUP BY
					DATE_TRUNC('months', ORDER_DATE),
					EXTRACT(
						YEAR
						FROM
							ORDER_DATE
					)
			) PREV
		WHERE
			PREV.YEAR_NO = CURR.YEAR_NO - 1
	)
ORDER BY
	CURR.MONTH;

-- ANSWER 24
SELECT
	CUST_ID,
	SUM(NET_TOTAL) AS TOTAL_SPEND,
	COUNT(ORDER_ID) AS ORDER_COUNT,
	ROUND(AVG(NET_TOTAL), 2) AS AVG_ORDER_VALUE,
	CURRENT_DATE - MIN(ORDER_DATE) AS DAYS_SINCE_FIRST_ORDER,
	CURRENT_DATE - MAX(ORDER_DATE) AS DAYS_SINCE_LAST_ORDER,
	CASE
		WHEN AVG(NET_TOTAL) > (
			SELECT
				AVG(NET_TOTAL)
			FROM
				SALES.ORDERS
		) THEN 'High Value'
		WHEN COUNT(ORDER_ID) > 3 THEN 'Growth'
		ELSE 'At Risk'
	END AS CLASSIFICATION
FROM
	SALES.ORDERS
GROUP BY
	CUST_ID
ORDER BY
	AVG_ORDER_VALUE DESC;

-- ANSWER 25
SELECT
	EMPLOYEE_ID,
	FIRST_NAME,
	SALARY,
	DEPT.DEPT_AVG,
	COMP.COMP_AVG,
	CASE
		WHEN SALARY > DEPT.DEPT_AVG
		AND SALARY > COMP.COMP_AVG THEN 'Above Both'
		WHEN SALARY > DEPT.DEPT_AVG
		AND SALARY < COMP.COMP_AVG THEN 'Above Department Average only'
		WHEN SALARY < DEPT.DEPT_AVG
		AND SALARY > COMP.COMP_AVG THEN 'Above Company Average only'
		ELSE 'Below Both'
	END AS CLASSIFICATION
FROM
	STORES.EMPLOYEES
	JOIN (
		SELECT
			DEPT_ID,
			ROUND(AVG(SALARY), 2) AS DEPT_AVG
		FROM
			STORES.EMPLOYEES
		GROUP BY
			DEPT_ID
	) DEPT USING (DEPT_ID)
	CROSS JOIN (
		SELECT
			ROUND(AVG(SALARY), 2) AS COMP_AVG
		FROM
			STORES.EMPLOYEES
	) COMP

-- ANSWER 26
SELECT
	EMP.STORE_ID,
	EMP.EMP_AVG_SALARY,
	COMP.COMP_AVG_SALARY,
	ABS(EMP.EMP_AVG_SALARY - COMP.COMP_AVG_SALARY) AS AVG_SALARY_DIFFERENCE,
	STORE.TOTAL_REVENUE,
	STORE2.AVG_REVENUE,
	ABS(STORE.TOTAL_REVENUE - STORE2.AVG_REVENUE) AS AVG_REVENUE_DIFFERENCE
FROM
	(
		SELECT
			STORE_ID,
			ROUND(AVG(SALARY), 2) AS EMP_AVG_SALARY
		FROM
			STORES.EMPLOYEES
		GROUP BY
			STORE_ID
	) EMP
	CROSS JOIN (
		SELECT
			ROUND(AVG(SALARY), 2) AS COMP_AVG_SALARY
		FROM
			STORES.EMPLOYEES
	) COMP
	JOIN (
		SELECT
			STORE_ID,
			ROUND(SUM(NET_TOTAL), 2) AS TOTAL_REVENUE
		FROM
			SALES.ORDERS
		GROUP BY
			STORE_ID
	) STORE USING (STORE_ID)
	CROSS JOIN (
		SELECT
			ROUND(AVG(T.TOTAL_REVENUE), 2) AS AVG_REVENUE
		FROM
			(
				SELECT
					STORE_ID,
					ROUND(SUM(NET_TOTAL), 2) AS TOTAL_REVENUE
				FROM
					SALES.ORDERS
				GROUP BY
					STORE_ID
			) T
	) STORE2
ORDER BY
	STORE.TOTAL_REVENUE,
	STORE2.AVG_REVENUE DESC;

-- ANSWER 27
SELECT
	S.STORE_ID,
	S.STORE_NAME,
	R.REGION_NAME,
	EMP.HEADCOUNT,
	EMP.AVG_SALARY,
	ORD.REVENUE,
	ORD.ORDER_COUNT,
	RET.TOTAL_RETURNED,
	RET.TOTAL_RETURNED::NUMERIC / ORD.ORDER_COUNT AS RETURN_RATE,
	SUPP.AVG_TICKET_RESOLUTION_HRS,
	CASE
		WHEN ORD.REVENUE > 100000
		AND (
			RET.TOTAL_RETURNED::NUMERIC / NULLIF(ORD.ORDER_COUNT, 0)
		) < 0.05 THEN 'Excellent'
		WHEN ORD.REVENUE > 50000
		OR (
			RET.TOTAL_RETURNED::NUMERIC / NULLIF(ORD.ORDER_COUNT, 0)
		) < 0.10 THEN 'Healthy'
		WHEN ORD.REVENUE IS NULL THEN 'No Data'
		ELSE 'Needs Attention'
	END AS STORE_HEALTH_SCORE
FROM
	STORES.STORES S
	LEFT JOIN CORE.DIM_REGION R USING (REGION_ID)
	LEFT JOIN (
		SELECT
			STORE_ID,
			COUNT(*) AS HEADCOUNT,
			ROUND(AVG(SALARY), 0) AS AVG_SALARY
		FROM
			STORES.EMPLOYEES
		GROUP BY
			STORE_ID
	) EMP USING (STORE_ID)
	LEFT JOIN (
		SELECT
			STORE_ID,
			COUNT(*) AS ORDER_COUNT,
			SUM(NET_TOTAL) AS REVENUE
		FROM
			SALES.ORDERS
		GROUP BY
			STORE_ID
	) ORD USING (STORE_ID)
	LEFT JOIN (
		SELECT
			STORE_ID,
			COUNT(*) AS TOTAL_RETURNED
		FROM
			SALES.RETURNS
			JOIN SALES.ORDERS USING (ORDER_ID)
		GROUP BY
			STORE_ID
	) RET USING (STORE_ID)
	LEFT JOIN (
		SELECT
			E.STORE_ID,
			ROUND(
				AVG(
					ROUND(
						EXTRACT(
							'EPOCH'
							FROM
								RESOLVED_DATE - CREATED_DATE
						) / 3600,
						1
					)
				),
				2
			) AS AVG_TICKET_RESOLUTION_HRS
		FROM
			SUPPORT.TICKETS T
			LEFT JOIN STORES.EMPLOYEES E ON E.EMPLOYEE_ID = T.AGENT_ID
		GROUP BY
			STORE_ID
	) SUPP USING (STORE_ID)